import React from "react";

export const styles: Record<string, React.CSSProperties> = {
  mask: {
    position: "fixed",
    inset: 0,
    background: "rgba(15,23,42,0.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: 20,
  },
  modal: {
    width: "min(720px, 100%)",
    maxHeight: "90vh",
    background: "#fff",
    borderRadius: 14,
    boxShadow: "0 16px 48px rgba(0,0,0,0.18)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  header: {
    padding: "18px 20px",
    borderBottom: "1px solid #f0f0f0",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  title: { margin: 0, fontSize: 18, color: "#1a1a2e" },
  sub: { margin: "4px 0 0", fontSize: 12, color: "#8c8c8c" },
  closeBtn: {
    border: "1px solid #d9d9d9",
    background: "#fff",
    borderRadius: 6,
    padding: "6px 12px",
    cursor: "pointer",
    fontSize: 13,
  },
  tabs: {
    display: "flex",
    gap: 8,
    padding: "12px 20px 0",
    flexWrap: "wrap" as const,
  },
  tab: {
    border: "1px solid #d9d9d9",
    background: "#fff",
    color: "#595959",
    borderRadius: 16,
    padding: "6px 14px",
    cursor: "pointer",
    fontSize: 13,
  },
  tabActive: {
    border: "1px solid #1677ff",
    background: "#e6f4ff",
    color: "#1677ff",
    borderRadius: 16,
    padding: "6px 14px",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
  },
  body: { padding: 20, overflowY: "auto" as const, flex: 1 },
  tip: { fontSize: 12, color: "#8c8c8c", margin: "0 0 12px", lineHeight: 1.6 },
  providerList: { display: "flex", flexDirection: "column" as const, gap: 10 },
  rpmBox: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: 12,
    marginBottom: 10,
    background: "#f7fbff",
    border: "1px solid #d6e4ff",
    borderRadius: 8,
  },
  rpmSelect: {
    minWidth: 130,
    padding: "7px 9px",
    border: "1px solid #91caff",
    borderRadius: 6,
    background: "#fff",
    color: "#262626",
    fontSize: 13,
    outline: "none",
  },
  providerCard: {
    border: "1px solid #f0f0f0",
    borderRadius: 8,
    padding: 12,
    background: "#fcfcfc",
  },
  providerHeader: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    marginBottom: 8,
  },
  providerBadge: {
    fontSize: 11,
    color: "#fff",
    background: "#1677ff",
    borderRadius: 4,
    padding: "2px 6px",
  },
  enableLabel: {
    fontSize: 12,
    color: "#595959",
    display: "flex",
    alignItems: "center",
    gap: 4,
    whiteSpace: "nowrap" as const,
  },
  formGroup: { display: "flex", flexDirection: "column" as const, gap: 10 },
  field: { display: "flex", flexDirection: "column" as const, gap: 4, flex: 1 },
  label: { fontSize: 12, color: "#8c8c8c" },
  input: {
    padding: "8px 10px",
    border: "1px solid #d9d9d9",
    borderRadius: 6,
    fontSize: 13,
    outline: "none",
    width: "100%",
    boxSizing: "border-box" as const,
  },
  actions: {
    display: "flex",
    gap: 8,
    marginTop: 10,
    flexWrap: "wrap" as const,
  },
  miniBtn: {
    fontSize: 12,
    color: "#1677ff",
    background: "#e6f4ff",
    border: "1px solid #91caff",
    borderRadius: 4,
    padding: "4px 10px",
    cursor: "pointer",
  },
  miniDangerBtn: {
    fontSize: 12,
    color: "#ff4d4f",
    background: "#fff1f0",
    border: "1px solid #ffa39e",
    borderRadius: 4,
    padding: "4px 10px",
    cursor: "pointer",
  },
  miniPrimaryBtn: {
    fontSize: 12,
    color: "#fff",
    background: "#1677ff",
    border: "1px solid #1677ff",
    borderRadius: 4,
    padding: "4px 10px",
    cursor: "pointer",
  },
  modeRow: { display: "flex", gap: 8, marginBottom: 12 },
  modeBtn: {
    flex: 1,
    padding: "8px 0",
    border: "1px solid #d9d9d9",
    borderRadius: 6,
    background: "#fff",
    color: "#595959",
    cursor: "pointer",
    fontSize: 14,
  },
  modeActive: {
    flex: 1,
    padding: "8px 0",
    border: "1px solid #1677ff",
    borderRadius: 6,
    background: "#e6f4ff",
    color: "#1677ff",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 500,
  },
  row: { display: "flex", gap: 12 },
  optionBox: {
    marginTop: 12,
    padding: 12,
    background: "#f7fbff",
    border: "1px solid #d6e4ff",
    borderRadius: 8,
    cursor: "pointer",
  },
  localSummaryBox: {
    marginTop: 8,
    padding: 12,
    background: "#f7fbff",
    border: "1px solid #d6e4ff",
    borderRadius: 8,
  },
  localHwGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
    marginTop: 10,
  },
  localHwItem: {
    background: "#fff",
    border: "1px solid #eef2f7",
    borderRadius: 6,
    padding: 8,
  },
  localHwValue: {
    fontSize: 12,
    color: "#262626",
    marginTop: 4,
    lineHeight: 1.5,
  },
  localRecCard: { border: "1px solid #91caff", background: "#f0f7ff" },
  localPresetMeta: {
    fontSize: 12,
    color: "#595959",
    lineHeight: 1.6,
    marginBottom: 4,
  },
  localTipsBox: {
    marginTop: 12,
    padding: 12,
    background: "#fafafa",
    border: "1px solid #f0f0f0",
    borderRadius: 8,
  },
  localTipsList: { margin: "8px 0 0", paddingLeft: 18 },
  localTipItem: {
    fontSize: 12,
    color: "#595959",
    marginBottom: 6,
    lineHeight: 1.5,
  },
  guideHero: {
    padding: 14,
    background: "linear-gradient(135deg, #f0f7ff 0%, #f6ffed 100%)",
    border: "1px solid #b7d8ff",
    borderRadius: 10,
  },
  guideCompareGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
    marginTop: 12,
  },
  guideCompareItem: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    padding: 10,
    background: "#fff",
    border: "1px solid #e8edf3",
    borderRadius: 8,
    fontSize: 12,
    color: "#595959",
    lineHeight: 1.5,
  },
  guideSection: {
    marginTop: 12,
    padding: 14,
    border: "1px solid #f0f0f0",
    borderRadius: 10,
    background: "#fcfcfc",
  },
  guideTitle: { fontSize: 15, fontWeight: 600, color: "#1f1f1f" },
  guideList: { margin: "10px 0 0", paddingLeft: 22 },
  guideItem: {
    fontSize: 12,
    color: "#595959",
    marginBottom: 8,
    lineHeight: 1.7,
  },
  inlineCode: {
    padding: "1px 5px",
    borderRadius: 4,
    background: "#f0f0f0",
    color: "#262626",
    wordBreak: "break-all" as const,
  },
  modelStatus: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    marginTop: 12,
    padding: 10,
    border: "1px solid #ffd591",
    background: "#fff7e6",
    borderRadius: 8,
  },
  modelStatusOk: { border: "1px solid #b7eb8f", background: "#f6ffed" },
  pathBox: {
    marginTop: 8,
    padding: 9,
    background: "#1f2937",
    color: "#e5e7eb",
    borderRadius: 6,
    fontSize: 11,
    fontFamily: "Consolas, monospace",
    wordBreak: "break-all" as const,
  },
  guideWarning: {
    marginTop: 10,
    padding: 10,
    background: "#fffbe6",
    border: "1px solid #ffe58f",
    borderRadius: 8,
    color: "#7c5b00",
    fontSize: 12,
    lineHeight: 1.6,
  },
  errorGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 8,
    marginTop: 10,
  },
  aboutCard: {
    padding: 14,
    background: "linear-gradient(135deg, #f7fbff 0%, #eef5ff 100%)",
    border: "1px solid #d6e4ff",
    borderRadius: 10,
  },
  aboutTitleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  aboutAppName: { fontSize: 18, fontWeight: 700, color: "#1a1a2e" },
  aboutSub: { fontSize: 12, color: "#8c8c8c", marginTop: 4 },
  aboutVersion: {
    fontSize: 12,
    color: "#1677ff",
    background: "#e6f4ff",
    border: "1px solid #91caff",
    borderRadius: 999,
    padding: "4px 10px",
    whiteSpace: "nowrap" as const,
  },
  aboutMeta: { marginTop: 12, fontSize: 12, color: "#595959", lineHeight: 1.8 },
  aboutLinks: {
    display: "flex",
    gap: 8,
    marginTop: 14,
    flexWrap: "wrap" as const,
    justifyContent: "flex-start",
  },
  aboutThanks: {
    marginTop: 14,
    padding: 14,
    background: "#fffbe6",
    border: "1px solid #ffe58f",
    borderRadius: 10,
  },
  aboutThanksText: {
    fontSize: 12,
    color: "#7c5b00",
    lineHeight: 1.7,
    marginTop: 6,
  },
  aboutLink: {
    color: "#1677ff",
    textDecoration: "underline",
    cursor: "pointer",
  },
  aboutList: { margin: "8px 0 0", paddingLeft: 18 },
  aboutListItem: {
    fontSize: 12,
    color: "#8c8c8c",
    marginBottom: 6,
    lineHeight: 1.5,
  },
  sectionDivider: {
    marginTop: 16,
    padding: 16,
    background: "#fafafa",
    border: "1px solid #f0f0f0",
    borderRadius: 10,
  },
  switchRow: { display: "flex", alignItems: "center", gap: 12 },
  switchTrack: {
    width: 42,
    height: 24,
    borderRadius: 12,
    background: "#d9d9d9",
    position: "relative" as const,
    transition: "all 0.2s",
    flexShrink: 0,
  },
  switchTrackOn: { background: "#1677ff" },
  switchThumb: {
    width: 18,
    height: 18,
    borderRadius: 9,
    background: "#fff",
    position: "absolute" as const,
    top: 3,
    left: 3,
    transition: "all 0.2s",
    boxShadow: "0 1px 3px rgba(0,0,0,0.2)",
  },
  switchThumbOn: { left: 21 },
  switchTitle: { fontSize: 14, color: "#262626", fontWeight: 500 },
  switchDesc: { fontSize: 12, color: "#8c8c8c", marginTop: 2 },
  msg: {
    fontSize: 12,
    color: "#595959",
    marginTop: 12,
    whiteSpace: "pre-wrap" as const,
  },
  err: {
    fontSize: 12,
    color: "#ff4d4f",
    marginTop: 8,
    whiteSpace: "pre-wrap" as const,
  },
  footer: {
    padding: "12px 20px",
    borderTop: "1px solid #f0f0f0",
    display: "flex",
    justifyContent: "flex-end",
  },
  saveBtn: {
    background: "#1677ff",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    padding: "8px 18px",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 500,
  },
  progressBox: {
    marginTop: 10,
    padding: "10px 14px",
    background: "#f8fafc",
    borderRadius: 8,
    border: "1px solid #e2e8f0",
  },
  progressBar: {
    height: 6,
    borderRadius: 3,
    background: "#e2e8f0",
    overflow: "hidden" as const,
    margin: "6px 0",
  },
  progressFill: {
    height: "100%",
    background: "#1677ff",
    borderRadius: 3,
    transition: "width 0.3s ease",
  },
};
